// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-4)
// protocol is simulatable under MLWE(56,31,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(20,183,2^(54.010685))
// 
// Ring
// degree d = 64
// modulus q = 1237940039285380274899125181, log(q) ~ 90.0
// factors q = q1
// 
// Compression
// D = 30
// gamma = 462678895690, log(gamma) ~ 38.75122
// 
// Dimensions of secrets
// s1: m1 = 96
// m: l = 0
// s2: m2 = 87
// 
// Size of secrets
// l2(s1) <= alpha = 53687091.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 32)
// exact euclidean: yes (dimensions: [32, 32], bounds: [198.4, 53687091.0])
// approximate infinity: yes (psi: 2797.9254, dimension: 64, bound: 1.6492674e+11)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 106515188940.8, log(stdev1/1.55) = 36.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 3328599654.4, log(stdev3/1.55) = 31.0
// stdev4 = 13633944184422.4, log(stdev4/1.55) = 43.0
// 
// Repetition rate
// M1 = 2.5757361
// M2 = 3.8719608
// M3 = 1.0448095
// M4 = 1.0249634
// total = 10.68016
// 
// Security
// MSIS dimension: 20
// MSIS root hermite factor: 1.0043977
// MLWE dimension: 56
// MLWE root hermite factor: 1.0043992
// 
// Proof size
// ~ 60.0156250000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633, 1125899906826241]
// bit length of products: [49, 99, 149, 199]
// inverses: [1, -162099428551732, 296975494591860, 32272507837893]

#include "lazer.h"
static const limb_t _param_q_limbs[] = {957UL, 67108864UL};
static const int_t _param_q = {{(limb_t *)_param_q_limbs, 2, 0}};
static const limb_t _param_qminus1_limbs[] = {956UL, 67108864UL};
static const int_t _param_qminus1 = {{(limb_t *)_param_qminus1_limbs, 2, 0}};
static const limb_t _param_m_limbs[] = {2675592188918022UL, 0UL};
static const int_t _param_m = {{(limb_t *)_param_m_limbs, 2, 0}};
static const limb_t _param_mby2_limbs[] = {1337796094459011UL, 0UL};
static const int_t _param_mby2 = {{(limb_t *)_param_mby2_limbs, 2, 0}};
static const limb_t _param_gamma_limbs[] = {462678895690UL, 0UL};
static const int_t _param_gamma = {{(limb_t *)_param_gamma_limbs, 2, 0}};
static const limb_t _param_gammaby2_limbs[] = {231339447845UL, 0UL};
static const int_t _param_gammaby2 = {{(limb_t *)_param_gammaby2_limbs, 2, 0}};
static const limb_t _param_pow2D_limbs[] = {1073741824UL, 0UL};
static const int_t _param_pow2D = {{(limb_t *)_param_pow2D_limbs, 2, 0}};
static const limb_t _param_pow2Dby2_limbs[] = {536870912UL, 0UL};
static const int_t _param_pow2Dby2 = {{(limb_t *)_param_pow2Dby2_limbs, 2, 0}};
static const limb_t _param_Bsq_limbs[] = {6707992479365989645UL, 6518612UL, 0UL, 0UL};
static const int_t _param_Bsq = {{(limb_t *)_param_Bsq_limbs, 4, 0}};
static const limb_t _param_scM1_limbs[] = {6667453644839222867UL, 10620455750038717401UL, 2UL};
static const int_t _param_scM1 = {{(limb_t *)_param_scM1_limbs, 3, 0}};
static const limb_t _param_scM2_limbs[] = {5339193006037497851UL, 16084837039329343588UL, 3UL};
static const int_t _param_scM2 = {{(limb_t *)_param_scM2_limbs, 3, 0}};
static const limb_t _param_scM3_limbs[] = {10692961739864675223UL, 826588887379630158UL, 1UL};
static const int_t _param_scM3 = {{(limb_t *)_param_scM3_limbs, 3, 0}};
static const limb_t _param_scM4_limbs[] = {13083039284862460048UL, 460493977795706294UL, 1UL};
static const int_t _param_scM4 = {{(limb_t *)_param_scM4_limbs, 3, 0}};
static const limb_t _param_stdev1sq_limbs[] = {737869762948382065UL, 615UL, 0UL, 0UL};
static const int_t _param_stdev1sq = {{(limb_t *)_param_stdev1sq_limbs, 4, 0}};
static const limb_t _param_stdev2sq_limbs[] = {40307261UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev2sq = {{(limb_t *)_param_stdev2sq_limbs, 4, 0}};
static const limb_t _param_stdev3sq_limbs[] = {11079575659271799439UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev3sq = {{(limb_t *)_param_stdev3sq_limbs, 4, 0}};
static const limb_t _param_stdev4sq_limbs[] = {6640827866535438582UL, 10076815UL, 0UL, 0UL};
static const int_t _param_stdev4sq = {{(limb_t *)_param_stdev4sq_limbs, 4, 0}};
static const limb_t _param_inv2_limbs[] = {478UL, 33554432UL};
static const int_t _param_inv2 = {{(limb_t *)_param_inv2_limbs, 2, 1}};
static const limb_t _param_inv4_limbs[] = {239UL, 16777216UL};
static const int_t _param_inv4 = {{(limb_t *)_param_inv4_limbs, 2, 1}};
static const unsigned int _param_n[2] = {32, 32};
static const limb_t _param_Bz3sqr_limbs[] = {10199131011377716250UL, 413UL, 0UL, 0UL};
static const int_t _param_Bz3sqr = {{(limb_t *)_param_Bz3sqr_limbs, 4, 0}};
static const limb_t _param_Bz4_limbs[] = {218143106950758UL, 0UL};
static const int_t _param_Bz4 = {{(limb_t *)_param_Bz4_limbs, 2, 0}};
static const limb_t _param_l2Bsq0_limbs[] = {39363UL, 0UL};
static const int_t _param_l2Bsq0 = {{(limb_t *)_param_l2Bsq0_limbs, 2, 0}};
static const limb_t _param_l2Bsq1_limbs[] = {2882303716496507UL, 0UL};
static const int_t _param_l2Bsq1 = {{(limb_t *)_param_l2Bsq1_limbs, 2, 0}};
static const int_srcptr _param_l2Bsq[] = {_param_l2Bsq0, _param_l2Bsq1};
static const polyring_t _param_ring = {{_param_q, 64, 91, 6, moduli_d64, 4, _param_inv2}};
static const dcompress_params_t _param_dcomp = {{ _param_q, _param_qminus1, _param_m, _param_mby2, _param_gamma, _param_gammaby2, _param_pow2D, _param_pow2Dby2, 30, 0, 52 }};
static const abdlop_params_t _param_tbox = {{ _param_ring, _param_dcomp, 98, 87, 0, 11, 20, _param_Bsq, 1, 8, 5, 140, 1, 36, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_eval_ = {{ _param_ring, _param_dcomp, 98, 87, 9, 2, 20, _param_Bsq, 1, 8, 5, 140, 1, 36, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_many_ = {{ _param_ring, _param_dcomp, 98, 87, 10, 1, 20, _param_Bsq, 1, 8, 5, 140, 1, 36, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const lnp_quad_eval_params_t _param_quad_eval = {{ _param_quad_eval_, _param_quad_many_, 2}};
static const lnp_tbox_params_t _param = {{ _param_tbox, _param_quad_eval, 32, _param_n, 64, 2, 98, 2, 31, _param_scM3, _param_stdev3sq, 2, 43, _param_scM4, _param_stdev4sq, _param_Bz3sqr, _param_Bz4, &_param_l2Bsq[0], _param_inv4, 61456UL }};

static const unsigned int param_Ps[32] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31};
static const unsigned int param_Es0[32] = {32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63};
static const unsigned int param_Es1[32] = {64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95};
static const unsigned int *param_Es[2] = { param_Es0, param_Es1, };
static const unsigned int param_Es_nrows[2] = {32, 32};

static const limb_t param_p_limbs[] = {1099511629429UL};
static const int_t param_p = {{(limb_t *)param_p_limbs, 1, 0}};
static const limb_t param_pinv_limbs[] = {16330387267126636734UL, 3276375UL};
static const int_t param_pinv = {{(limb_t *)param_pinv_limbs, 2, 0}};
static const unsigned int param_s1_indices[3] = {0, 1, 2};
static const lin_params_t param = {{ _param, 2048, param_p, param_pinv, 32, param_s1_indices, 3, NULL, 0,  param_Ps, 32, param_Es, param_Es_nrows, NULL, NULL }};

