// auto-generated by lnp-quad-eval-codegen.sage from ../vdec/vdec_params.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-4)
// protocol is simulatable under MLWE(38,20,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0)
// 
// Ring
// degree d = 64
// modulus q = 1152921504606847301, log(q) ~ 60.0
// factors q = q1
// 
// Compression
// D = 9
// gamma = 514420, log(gamma) ~ 18.972587
// m = (q-1)/gamma = 2241206610565, log(m) ~ 41.027413
// 
// Dimensions of secrets
// s1: m1 = 32
// m: l = 5
// s2: m2 = 58
// 
// Size of secrets
// l2(s1) <= alpha = 1.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 1587.2, log(stdev1/1.55) = 10.0
// stdev2 = 101580.8, log(stdev2/1.55) = 16.0
// 
// Repetition rate
// M1 = 3.2656121
// M2 = 3.0846257
// M4 = 1.0448095
// total = 10.524565
// 
// Security
// MSIS dimension: 12
// MSIS root hermite factor: 1.0043921
// MLWE dimension: 38
// MLWE root hermite factor: 1.004348
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t params1_q_limbs[] = {1152921504606847301UL};
static const int_t params1_q = {{(limb_t *)params1_q_limbs, 1, 0}};
static const limb_t params1_qminus1_limbs[] = {1152921504606847300UL};
static const int_t params1_qminus1 = {{(limb_t *)params1_qminus1_limbs, 1, 0}};
static const limb_t params1_m_limbs[] = {2241206610565UL};
static const int_t params1_m = {{(limb_t *)params1_m_limbs, 1, 0}};
static const limb_t params1_mby2_limbs[] = {0};
static const int_t params1_mby2 = {{(limb_t *)params1_mby2_limbs, 1, 0}};
static const limb_t params1_gamma_limbs[] = {514420UL};
static const int_t params1_gamma = {{(limb_t *)params1_gamma_limbs, 1, 0}};
static const limb_t params1_gammaby2_limbs[] = {257210UL};
static const int_t params1_gammaby2 = {{(limb_t *)params1_gammaby2_limbs, 1, 0}};
static const limb_t params1_pow2D_limbs[] = {512UL};
static const int_t params1_pow2D = {{(limb_t *)params1_pow2D_limbs, 1, 0}};
static const limb_t params1_pow2Dby2_limbs[] = {256UL};
static const int_t params1_pow2Dby2 = {{(limb_t *)params1_pow2Dby2_limbs, 1, 0}};
static const limb_t params1_Bsq_limbs[] = {284722069400870UL, 0UL};
static const int_t params1_Bsq = {{(limb_t *)params1_Bsq_limbs, 2, 0}};
static const limb_t params1_scM1_limbs[] = {14472152395081010487UL, 4899677638543494430UL, 3UL};
static const int_t params1_scM1 = {{(limb_t *)params1_scM1_limbs, 3, 0}};
static const limb_t params1_scM2_limbs[] = {10820872591325647227UL, 1561068125872041154UL, 3UL};
static const int_t params1_scM2 = {{(limb_t *)params1_scM2_limbs, 3, 0}};
static const limb_t params1_scM4_limbs[] = {12665361659720894108UL, 826588900563521044UL, 1UL};
static const int_t params1_scM4 = {{(limb_t *)params1_scM4_limbs, 3, 0}};
static const limb_t params1_stdev1sq_limbs[] = {2519204UL, 0UL};
static const int_t params1_stdev1sq = {{(limb_t *)params1_stdev1sq_limbs, 2, 0}};
static const limb_t params1_stdev2sq_limbs[] = {10318658929UL, 0UL};
static const int_t params1_stdev2sq = {{(limb_t *)params1_stdev2sq_limbs, 2, 0}};
static const limb_t params1_stdev4sq_limbs[] = {17708874310761169551UL, 660394171432UL};
static const int_t params1_stdev4sq = {{(limb_t *)params1_stdev4sq_limbs, 2, 0}};
static const limb_t params1_inv2_limbs[] = {576460752303423650UL};
static const int_t params1_inv2 = {{(limb_t *)params1_inv2_limbs, 1, 1}};
static const limb_t params1_inv4_limbs[] = {288230376151711825UL};
static const int_t params1_inv4 = {{(limb_t *)params1_inv4_limbs, 1, 1}};
static const limb_t params1_Bz4_limbs[] = {15482278514088131833UL, 454706217852438UL};
static const int_t params1_Bz4 = {{(limb_t *)params1_Bz4_limbs, 2, 0}};
static const polyring_t params1_ring = {{params1_q, 64, 61, 6, moduli_d64, 3, params1_inv2}};
static const dcompress_params_t params1_dcomp = {{ params1_q, params1_qminus1, params1_m, params1_mby2, params1_gamma, params1_gammaby2, params1_pow2D, params1_pow2Dby2, 9, 1, 42 }};
static const abdlop_params_t params1_quad_eval = {{ params1_ring, params1_dcomp, 32, 58, 5, 3, 12, params1_Bsq, 1, 8, 5, 140, 1, 10, params1_scM1, params1_stdev1sq, 1, 16, params1_scM2, params1_stdev2sq}};
static const abdlop_params_t params1_quad_many = {{ params1_ring, params1_dcomp, 32, 58, 7, 1, 12, params1_Bsq, 1, 8, 5, 140, 1, 10, params1_scM1, params1_stdev1sq, 1, 16, params1_scM2, params1_stdev2sq}};
static const lnp_quad_eval_params_t params1 = {{ params1_quad_eval, params1_quad_many, 4, params1_inv4, 51, params1_scM4, params1_stdev4sq, params1_Bz4}};

